//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxxor.PCL.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MxCurrencySymbol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MxCurrencySymbol() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maxxor.PCL.Resources.MxCurrencySymbol", typeof(MxCurrencySymbol).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.إ.
        /// </summary>
        public static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ؋.
        /// </summary>
        public static string AFN {
            get {
                return ResourceManager.GetString("AFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lek.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ֏.
        /// </summary>
        public static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAƒ.
        /// </summary>
        public static string ANG {
            get {
                return ResourceManager.GetString("ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kz.
        /// </summary>
        public static string AOA {
            get {
                return ResourceManager.GetString("AOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string ARS {
            get {
                return ResourceManager.GetString("ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afl..
        /// </summary>
        public static string AWG {
            get {
                return ResourceManager.GetString("AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to man..
        /// </summary>
        public static string AZN {
            get {
                return ResourceManager.GetString("AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        public static string BAM {
            get {
                return ResourceManager.GetString("BAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string BBD {
            get {
                return ResourceManager.GetString("BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ৳.
        /// </summary>
        public static string BDT {
            get {
                return ResourceManager.GetString("BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лв..
        /// </summary>
        public static string BGN {
            get {
                return ResourceManager.GetString("BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.ب.‏.
        /// </summary>
        public static string BHD {
            get {
                return ResourceManager.GetString("BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBu.
        /// </summary>
        public static string BIF {
            get {
                return ResourceManager.GetString("BIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string BMD {
            get {
                return ResourceManager.GetString("BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string BND {
            get {
                return ResourceManager.GetString("BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $b.
        /// </summary>
        public static string BOB {
            get {
                return ResourceManager.GetString("BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        public static string BRL {
            get {
                return ResourceManager.GetString("BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string BSD {
            get {
                return ResourceManager.GetString("BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu.
        /// </summary>
        public static string BTN {
            get {
                return ResourceManager.GetString("BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string BWP {
            get {
                return ResourceManager.GetString("BWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Br.
        /// </summary>
        public static string BYN {
            get {
                return ResourceManager.GetString("BYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZ$.
        /// </summary>
        public static string BZD {
            get {
                return ResourceManager.GetString("BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        public static string CDF {
            get {
                return ResourceManager.GetString("CDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr..
        /// </summary>
        public static string CHF {
            get {
                return ResourceManager.GetString("CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CLP {
            get {
                return ResourceManager.GetString("CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        public static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string COP {
            get {
                return ResourceManager.GetString("COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₡.
        /// </summary>
        public static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUC$.
        /// </summary>
        public static string CUC {
            get {
                return ResourceManager.GetString("CUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₱.
        /// </summary>
        public static string CUP {
            get {
                return ResourceManager.GetString("CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CVE {
            get {
                return ResourceManager.GetString("CVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kč.
        /// </summary>
        public static string CZK {
            get {
                return ResourceManager.GetString("CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fdj.
        /// </summary>
        public static string DJF {
            get {
                return ResourceManager.GetString("DJF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr..
        /// </summary>
        public static string DKK {
            get {
                return ResourceManager.GetString("DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RD$.
        /// </summary>
        public static string DOP {
            get {
                return ResourceManager.GetString("DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZD.
        /// </summary>
        public static string DZD {
            get {
                return ResourceManager.GetString("DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ج.م.‏.
        /// </summary>
        public static string EGP {
            get {
                return ResourceManager.GetString("EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nfk.
        /// </summary>
        public static string ERN {
            get {
                return ResourceManager.GetString("ERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETB.
        /// </summary>
        public static string ETB {
            get {
                return ResourceManager.GetString("ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string FJD {
            get {
                return ResourceManager.GetString("FJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string FKP {
            get {
                return ResourceManager.GetString("FKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₾.
        /// </summary>
        public static string GEL {
            get {
                return ResourceManager.GetString("GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string GGP {
            get {
                return ResourceManager.GetString("GGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GH¢.
        /// </summary>
        public static string GHS {
            get {
                return ResourceManager.GetString("GHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string GIP {
            get {
                return ResourceManager.GetString("GIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string GMD {
            get {
                return ResourceManager.GetString("GMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG.
        /// </summary>
        public static string GNF {
            get {
                return ResourceManager.GetString("GNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string GTQ {
            get {
                return ResourceManager.GetString("GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string GYD {
            get {
                return ResourceManager.GetString("GYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK$.
        /// </summary>
        public static string HKD {
            get {
                return ResourceManager.GetString("HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L..
        /// </summary>
        public static string HNL {
            get {
                return ResourceManager.GetString("HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kn.
        /// </summary>
        public static string HRK {
            get {
                return ResourceManager.GetString("HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string HTG {
            get {
                return ResourceManager.GetString("HTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ft.
        /// </summary>
        public static string HUF {
            get {
                return ResourceManager.GetString("HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rp.
        /// </summary>
        public static string IDR {
            get {
                return ResourceManager.GetString("IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₪.
        /// </summary>
        public static string ILS {
            get {
                return ResourceManager.GetString("ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string IMP {
            get {
                return ResourceManager.GetString("IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रु.
        /// </summary>
        public static string INR {
            get {
                return ResourceManager.GetString("INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.ع.‏.
        /// </summary>
        public static string IQD {
            get {
                return ResourceManager.GetString("IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال.
        /// </summary>
        public static string IRR {
            get {
                return ResourceManager.GetString("IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr..
        /// </summary>
        public static string ISK {
            get {
                return ResourceManager.GetString("ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string JEP {
            get {
                return ResourceManager.GetString("JEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J$.
        /// </summary>
        public static string JMD {
            get {
                return ResourceManager.GetString("JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.ا.‏.
        /// </summary>
        public static string JOD {
            get {
                return ResourceManager.GetString("JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        public static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KSh.
        /// </summary>
        public static string KES {
            get {
                return ResourceManager.GetString("KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сом.
        /// </summary>
        public static string KGS {
            get {
                return ResourceManager.GetString("KGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ៛.
        /// </summary>
        public static string KHR {
            get {
                return ResourceManager.GetString("KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        public static string KMF {
            get {
                return ResourceManager.GetString("KMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₩.
        /// </summary>
        public static string KPW {
            get {
                return ResourceManager.GetString("KPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₩.
        /// </summary>
        public static string KRW {
            get {
                return ResourceManager.GetString("KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.ك.‏.
        /// </summary>
        public static string KWD {
            get {
                return ResourceManager.GetString("KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string KYD {
            get {
                return ResourceManager.GetString("KYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        public static string KZT {
            get {
                return ResourceManager.GetString("KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₭.
        /// </summary>
        public static string LAK {
            get {
                return ResourceManager.GetString("LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ل.ل.‏.
        /// </summary>
        public static string LBP {
            get {
                return ResourceManager.GetString("LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to රු..
        /// </summary>
        public static string LKR {
            get {
                return ResourceManager.GetString("LKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string LRD {
            get {
                return ResourceManager.GetString("LRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string LSL {
            get {
                return ResourceManager.GetString("LSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.ل.‏.
        /// </summary>
        public static string LYD {
            get {
                return ResourceManager.GetString("LYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.م.‏.
        /// </summary>
        public static string MAD {
            get {
                return ResourceManager.GetString("MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDL.
        /// </summary>
        public static string MDL {
            get {
                return ResourceManager.GetString("MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar.
        /// </summary>
        public static string MGA {
            get {
                return ResourceManager.GetString("MGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ден..
        /// </summary>
        public static string MKD {
            get {
                return ResourceManager.GetString("MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string MMK {
            get {
                return ResourceManager.GetString("MMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₮.
        /// </summary>
        public static string MNT {
            get {
                return ResourceManager.GetString("MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOP.
        /// </summary>
        public static string MOP {
            get {
                return ResourceManager.GetString("MOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UM.
        /// </summary>
        public static string MRO {
            get {
                return ResourceManager.GetString("MRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rs.
        /// </summary>
        public static string MUR {
            get {
                return ResourceManager.GetString("MUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ރ..
        /// </summary>
        public static string MVR {
            get {
                return ResourceManager.GetString("MVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MK.
        /// </summary>
        public static string MWK {
            get {
                return ResourceManager.GetString("MWK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string MXN {
            get {
                return ResourceManager.GetString("MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM.
        /// </summary>
        public static string MYR {
            get {
                return ResourceManager.GetString("MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTn.
        /// </summary>
        public static string MZN {
            get {
                return ResourceManager.GetString("MZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string NAD {
            get {
                return ResourceManager.GetString("NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₦.
        /// </summary>
        public static string NGN {
            get {
                return ResourceManager.GetString("NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string NIO {
            get {
                return ResourceManager.GetString("NIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        public static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रु.
        /// </summary>
        public static string NPR {
            get {
                return ResourceManager.GetString("NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string NZD {
            get {
                return ResourceManager.GetString("NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ر.ع.‏.
        /// </summary>
        public static string OMR {
            get {
                return ResourceManager.GetString("OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/..
        /// </summary>
        public static string PAB {
            get {
                return ResourceManager.GetString("PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/..
        /// </summary>
        public static string PEN {
            get {
                return ResourceManager.GetString("PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string PGK {
            get {
                return ResourceManager.GetString("PGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhP.
        /// </summary>
        public static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rs.
        /// </summary>
        public static string PKR {
            get {
                return ResourceManager.GetString("PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zł.
        /// </summary>
        public static string PLN {
            get {
                return ResourceManager.GetString("PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gs.
        /// </summary>
        public static string PYG {
            get {
                return ResourceManager.GetString("PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ر.ق.‏.
        /// </summary>
        public static string QAR {
            get {
                return ResourceManager.GetString("QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lei.
        /// </summary>
        public static string RON {
            get {
                return ResourceManager.GetString("RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din..
        /// </summary>
        public static string RSD {
            get {
                return ResourceManager.GetString("RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р..
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWF.
        /// </summary>
        public static string RWF {
            get {
                return ResourceManager.GetString("RWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ر.س.‏.
        /// </summary>
        public static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string SBD {
            get {
                return ResourceManager.GetString("SBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        public static string SCR {
            get {
                return ResourceManager.GetString("SCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ج.س..
        /// </summary>
        public static string SDG {
            get {
                return ResourceManager.GetString("SDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        public static string SEK {
            get {
                return ResourceManager.GetString("SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string SGD {
            get {
                return ResourceManager.GetString("SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £.
        /// </summary>
        public static string SHP {
            get {
                return ResourceManager.GetString("SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le.
        /// </summary>
        public static string SLL {
            get {
                return ResourceManager.GetString("SLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh.
        /// </summary>
        public static string SOS {
            get {
                return ResourceManager.GetString("SOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string SRD {
            get {
                return ResourceManager.GetString("SRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db.
        /// </summary>
        public static string STD {
            get {
                return ResourceManager.GetString("STD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₡.
        /// </summary>
        public static string SVC {
            get {
                return ResourceManager.GetString("SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ل.س.‏.
        /// </summary>
        public static string SYP {
            get {
                return ResourceManager.GetString("SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string SZL {
            get {
                return ResourceManager.GetString("SZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฿.
        /// </summary>
        public static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to т.р..
        /// </summary>
        public static string TJS {
            get {
                return ResourceManager.GetString("TJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m..
        /// </summary>
        public static string TMT {
            get {
                return ResourceManager.GetString("TMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to د.ت.‏.
        /// </summary>
        public static string TND {
            get {
                return ResourceManager.GetString("TND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T$.
        /// </summary>
        public static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL.
        /// </summary>
        public static string TRY {
            get {
                return ResourceManager.GetString("TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT$.
        /// </summary>
        public static string TTD {
            get {
                return ResourceManager.GetString("TTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string TVD {
            get {
                return ResourceManager.GetString("TVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT$.
        /// </summary>
        public static string TWD {
            get {
                return ResourceManager.GetString("TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSh.
        /// </summary>
        public static string TZS {
            get {
                return ResourceManager.GetString("TZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₴.
        /// </summary>
        public static string UAH {
            get {
                return ResourceManager.GetString("UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USh.
        /// </summary>
        public static string UGX {
            get {
                return ResourceManager.GetString("UGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $U.
        /// </summary>
        public static string UYU {
            get {
                return ResourceManager.GetString("UYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so&apos;m.
        /// </summary>
        public static string UZS {
            get {
                return ResourceManager.GetString("UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bs. F..
        /// </summary>
        public static string VEF {
            get {
                return ResourceManager.GetString("VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₫.
        /// </summary>
        public static string VND {
            get {
                return ResourceManager.GetString("VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VT.
        /// </summary>
        public static string VUV {
            get {
                return ResourceManager.GetString("VUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS$.
        /// </summary>
        public static string WST {
            get {
                return ResourceManager.GetString("WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCFA.
        /// </summary>
        public static string XAF {
            get {
                return ResourceManager.GetString("XAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string XCD {
            get {
                return ResourceManager.GetString("XCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOF.
        /// </summary>
        public static string XOF {
            get {
                return ResourceManager.GetString("XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₣.
        /// </summary>
        public static string XPF {
            get {
                return ResourceManager.GetString("XPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ر.ي.‏.
        /// </summary>
        public static string YER {
            get {
                return ResourceManager.GetString("YER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string ZAR {
            get {
                return ResourceManager.GetString("ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZK.
        /// </summary>
        public static string ZMW {
            get {
                return ResourceManager.GetString("ZMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z$.
        /// </summary>
        public static string ZWD {
            get {
                return ResourceManager.GetString("ZWD", resourceCulture);
            }
        }
    }
}
